In [20]:
import numpy as np

1) Crie um NumPy array de uma dimensão com 5 elementos aleatórios entre 1 e 10

In [21]:
array = np.random.randint(1, 11, size=5)

print(array)


[1 8 6 2 1]


2) Crie um NumPy array bidimensional com 3 linhas e 4 colunas, preenchido com
zeros.

In [22]:
array = np.zeros((3, 4))

print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3) Crie um NumPy array bidimensional com 2 linhas e 3 colunas, preenchido com
números inteiros sequenciais de 1 a 6.

In [23]:
array = np.arange(1, 7).reshape(2, 3)

print(array)

[[1 2 3]
 [4 5 6]]


4) Crie um NumPy array bidimensional com 3 linhas e 4 colunas, preenchido com
números inteiros aleatórios entre 1 e 100.

In [24]:
array = np.random.randint(1, 101, size=(3, 4))

print(array)

[[97 99  8  1]
 [ 8 61 13 58]
 [13 90 24 27]]


5) Crie um NumPy array de uma dimensão com 10 elementos aleatórios entre 0 e
1, em seguida, calcule a média dos elementos.

In [30]:
arr = np.random.rand(10)
print(arr)
mean = np.mean(arr)
print(mean)

[0.62406481 0.34699855 0.62852526 0.86313268 0.4238181  0.43209191
 0.57632189 0.3474722  0.34224398 0.0388189 ]
0.46234882963587587


6) Crie um NumPy array de uma dimensão com 20 elementos aleatórios entre -5 e 5,
em seguida, substitua todos os valores negativos por zero.

In [34]:
arr = np.random.randint(-5, 6, 20)
print(arr)
arr[arr < 0] = 0
print(arr)

[-2 -5 -5  5  2 -1  0 -2 -1 -1  4  4 -5 -3  2  3  1 -3 -4 -5]
[0 0 0 5 2 0 0 0 0 0 4 4 0 0 2 3 1 0 0 0]


7) Crie um NumPy array bidimensional com 3 linhas e 4 colunas, preenchido com
números inteiros aleatórios entre -10 e 10, em seguida, calcule a soma dos
elementos em cada coluna.

In [27]:
arr = np.random.randint(-10, 11, (3, 4))
print(arr)
sum_col = np.sum(arr, axis=0)
print(sum_col)

[[ -9 -10   2   4]
 [  7  -1   1  -6]
 [  7   2   5  -5]]
[ 5 -9  8 -7]


8) Crie um NumPy array de uma dimensão com 15 elementos aleatórios entre 0 e 10,
em seguida, ordene os elementos em ordem crescente.


In [35]:
arr = np.random.randint(0, 11, 15)
print(arr)
arr.sort()
print(arr)

[ 1  0  6  4  8  0  4 10  1  6  5  3  8  8  0]
[ 0  0  0  1  1  3  4  4  5  6  6  8  8  8 10]


9) Crie um NumPy array de uma dimensão com 8 elementos aleatórios entre 1 e 100,
em seguida, encontre o índice do elemento com o valor máximo.

In [47]:
arr = np.random.randint(1, 101, 8)
print(arr)
max_index = np.argmax(arr)
print(max_index)

[71 56 19 34 88  8 68 62]
4


10) Crie um NumPy array de uma dimensão com 12 elementos aleatórios entre 1 e
20, em seguida, divida os elementos em 3 arrays iguais

In [59]:
arr = np.random.randint(1, 21, 12)
print(arr)
arr_reshape = arr.reshape((3, 4))
print(arr_reshape)

[ 9  7 16  2  1  7 11  5 15 19  7  5]
[[ 9  7 16  2]
 [ 1  7 11  5]
 [15 19  7  5]]
